---
- include: roles/common/tasks/install-full-instance.yml

- name: Populate Splunk configs
  template:
    src: "{{ item + '.j2' }}"
    dest: /opt/splunk/etc/system/local/{{ item }}
  with_items:
    - deploymentclient.conf
    - server.conf

- name: Populate indexes.conf to master-apps/
  template:
    src: "{{ item + '.j2' }}"
    dest: /opt/splunk/etc/master-apps/_cluster/local/{{ item }}
  with_items:
    - indexes.conf

- name: Start Splunk
  command: /opt/splunk/bin/splunk restart --accept-license  --answer-yes

- name: Enable boot-start
  command: /opt/splunk/bin/splunk enable boot-start

- include: roles/common/tasks/update_admin_password.yml

- name: Restart again to apply password change
  service:
    name: splunk
    state: restarted