# Install Splunk Enterprise
- name: Copy .deb file to server
  copy:
     src: roles/common/files/splunk-6.6.0-1c4f3bbe1aea-linux-2.6-amd64.deb
     dest: /tmp/

- name: Install Splunk-6.6.0
  apt:
    deb: /tmp/splunk-6.6.0-1c4f3bbe1aea-linux-2.6-amd64.deb