---
### change password
- name: Get hash of password
  shell: python -c "from string import ascii_letters;import crypt, getpass,pwd,random;print crypt.crypt('{{ splunk_new_password }}', '\$6\$'+''.join(random.choice(ascii_letters) for j in range(16))+'\$')"
  register: result

- name: Change password
  lineinfile:
    path: /opt/splunk/etc/passwd
    regexp: '^(:admin:)[^:]*(:.*)$'
    line: '\1{{ result.stdout }}\2'
    backrefs: yes