---
search_indexers: 
  - https://cluster-indexer-hq-afr.vir:8089
  - https://cluster-indexer-hq-mesa.vir:8089
  - https://cluster-indexer-hq-eur.vir:8089

# ldap strategies
strategies:
  - {
    strategy_name: ldapinho,
    SSLEnabled: 0,
    bindDN: "CN=Administrator,CN=Users,DC=st8,DC=org",
    bindDNpassword: "$1$jpqOOxxMXrNGG/U=",
    groupBaseDN: "CN=splunk,CN=Users,DC=st8,DC=org",
    groupMappingAttribute: dn,
    groupMemberAttribute: member,
    groupNameAttribute: samaccountname,
    host: 188.130.155.41,
    nestedGroups: 0,
    network_timeout: 20,
    port: 389,
    realNameAttribute: name,
    userBaseDN: "CN=Users,DC=st8,DC=org",
    userNameAttribute: samaccountname,
    ldap_group_name_user: splunk
  }